idf_component_register(
    SRCS
        "main.c"
        "wifi_ap.c"
        "udp_push.c"
        "camera_stream.c"
        "flight_control.c"
    INCLUDE_DIRS "."
    REQUIRES
        driver
        esp_timer
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        lwip
        icm20948
        espressif__esp32-camera
)
